NewSubsample <- read.csv("subsamp_3062583A1.csv")

graphNum=1
data1 = NewSubsample[NewSubsample$graph == graphNum,]
ns1 <- lm(lnF ~ dcsMeanDepth, data=data1)
newx <- seq(min(data1$dcsMeanDepth), max(data1$dcsMeanDepth), length.out=100)
preds <- predict(ns1, newdata = data.frame(dcsMeanDepth=newx), interval='confidence')
plot(data=data1, lnF ~ dcsMeanDepth)
polygon(c(rev(newx),newx),c(rev(preds[,3]),preds[,2]), col='grey80', border=NA)
lines(newx, preds[,3],lty='dashed', col='red')
lines(newx, preds[,2],lty='dashed', col='red')
abline(ns1, col='red')
points(lnF ~ dcsMeanDepth, data=data1)
summary(ns1)
confint(ns1)
min(data1$dcsMeanDepth)
max(data1$dcsMeanDepth)

graphNum=2
data2 = NewSubsample[NewSubsample$graph == graphNum,]
ns2 <- lm(lnF ~ dcsMeanDepth, data=data2)
newx <- seq(min(data2$dcsMeanDepth), max(data2$dcsMeanDepth), length.out=100)
preds <- predict(ns2, newdata = data.frame(dcsMeanDepth=newx), interval='confidence')
plot(data=data2, lnF ~ dcsMeanDepth)
polygon(c(rev(newx),newx),c(rev(preds[,3]),preds[,2]), col='grey80', border=NA)
lines(newx, preds[,3],lty='dashed', col='red')
lines(newx, preds[,2],lty='dashed', col='red')
abline(ns2, col='red')
points(lnF ~ dcsMeanDepth, data=data2)
summary(ns2)
confint(ns2)
min(data2$dcsMeanDepth)
max(data2$dcsMeanDepth)

graphNum=3
data3 = NewSubsample[NewSubsample$graph == graphNum,]
ns3 <- lm(lnF ~ dcsMeanDepth, data=data3)
newx <- seq(min(data3$dcsMeanDepth), max(data3$dcsMeanDepth), length.out=100)
preds <- predict(ns3, newdata = data.frame(dcsMeanDepth=newx), interval='confidence')
plot(data=data3, lnF ~ dcsMeanDepth)
polygon(c(rev(newx),newx),c(rev(preds[,3]),preds[,2]), col='grey80', border=NA)
lines(newx, preds[,3],lty='dashed', col='red')
lines(newx, preds[,2],lty='dashed', col='red')
abline(ns3, col='red')
points(lnF ~ dcsMeanDepth, data=data3)
summary(ns3)
confint(ns3)
min(data3$dcsMeanDepth)
max(data3$dcsMeanDepth)

ns4 <- lm(NewSubsample$lnF ~ NewSubsample$dcsMeanDepth)
newx <- seq(min(NewSubsample$dcsMeanDepth), max(NewSubsample$dcsMeanDepth), length.out=100)
preds <- predict(ns3, newdata = data.frame(dcsMeanDepth=newx), interval='confidence')
plot(NewSubsample$lnF ~ NewSubsample$dcsMeanDepth)
polygon(c(rev(newx),newx),c(rev(preds[,3]),preds[,2]), col='grey80', border=NA)
lines(newx, preds[,3],lty='dashed', col='red')
lines(newx, preds[,2],lty='dashed', col='red')
abline(ns3, col='red')
points(NewSubsample$lnF ~ NewSubsample$dcsMeanDepth)
summary(ns4)
confint(ns4)
min(NewSubsample$dcsMeanDepth)
max(NewSubsample$dcsMeanDepth)


NewSubsample <- read.csv("subsamp_3070030A1.csv")

graphNum=1
data1 = NewSubsample[NewSubsample$graph == graphNum,]
ns1 <- lm(lnF ~ dcsMeanDepth, data=data1)
newx <- seq(min(data1$dcsMeanDepth), max(data1$dcsMeanDepth), length.out=100)
preds <- predict(ns1, newdata = data.frame(dcsMeanDepth=newx), interval='confidence')
plot(data=data1, lnF ~ dcsMeanDepth)
polygon(c(rev(newx),newx),c(rev(preds[,3]),preds[,2]), col='grey80', border=NA)
lines(newx, preds[,3],lty='dashed', col='red')
lines(newx, preds[,2],lty='dashed', col='red')
abline(ns1, col='red')
points(lnF ~ dcsMeanDepth, data=data1)
summary(ns1)
confint(ns1)
min(data1$dcsMeanDepth)
max(data1$dcsMeanDepth)

graphNum=2
data2 = NewSubsample[NewSubsample$graph == graphNum,]
ns2 <- lm(lnF ~ dcsMeanDepth, data=data2)
newx <- seq(min(data2$dcsMeanDepth), max(data2$dcsMeanDepth), length.out=100)
preds <- predict(ns2, newdata = data.frame(dcsMeanDepth=newx), interval='confidence')
plot(data=data2, lnF ~ dcsMeanDepth)
polygon(c(rev(newx),newx),c(rev(preds[,3]),preds[,2]), col='grey80', border=NA)
lines(newx, preds[,3],lty='dashed', col='red')
lines(newx, preds[,2],lty='dashed', col='red')
abline(ns2, col='red')
points(lnF ~ dcsMeanDepth, data=data2)
summary(ns2)
confint(ns2)
min(data2$dcsMeanDepth)
max(data2$dcsMeanDepth)

graphNum=3
data3 = NewSubsample[NewSubsample$graph == graphNum,]
ns3 <- lm(lnF ~ dcsMeanDepth, data=data3)
newx <- seq(min(data3$dcsMeanDepth), max(data3$dcsMeanDepth), length.out=100)
preds <- predict(ns3, newdata = data.frame(dcsMeanDepth=newx), interval='confidence')
plot(data=data3, lnF ~ dcsMeanDepth)
polygon(c(rev(newx),newx),c(rev(preds[,3]),preds[,2]), col='grey80', border=NA)
lines(newx, preds[,3],lty='dashed', col='red')
lines(newx, preds[,2],lty='dashed', col='red')
abline(ns3, col='red')
points(lnF ~ dcsMeanDepth, data=data3)
summary(ns3)
confint(ns3)
min(data3$dcsMeanDepth)
max(data3$dcsMeanDepth)

ns4 <- lm(NewSubsample$lnF ~ NewSubsample$dcsMeanDepth)
newx <- seq(min(NewSubsample$dcsMeanDepth), max(NewSubsample$dcsMeanDepth), length.out=100)
preds <- predict(ns3, newdata = data.frame(dcsMeanDepth=newx), interval='confidence')
plot(NewSubsample$lnF ~ NewSubsample$dcsMeanDepth)
polygon(c(rev(newx),newx),c(rev(preds[,3]),preds[,2]), col='grey80', border=NA)
lines(newx, preds[,3],lty='dashed', col='red')
lines(newx, preds[,2],lty='dashed', col='red')
abline(ns3, col='red')
points(NewSubsample$lnF ~ NewSubsample$dcsMeanDepth)
summary(ns4)
confint(ns4)
min(NewSubsample$dcsMeanDepth)
max(NewSubsample$dcsMeanDepth)


NewSubsample <- read.csv("subsamp_3070052A1.csv")

graphNum=1
data1 = NewSubsample[NewSubsample$graph == graphNum,]
ns1 <- lm(lnF ~ dcsMeanDepth, data=data1)
newx <- seq(min(data1$dcsMeanDepth), max(data1$dcsMeanDepth), length.out=100)
preds <- predict(ns1, newdata = data.frame(dcsMeanDepth=newx), interval='confidence')
plot(data=data1, lnF ~ dcsMeanDepth)
polygon(c(rev(newx),newx),c(rev(preds[,3]),preds[,2]), col='grey80', border=NA)
lines(newx, preds[,3],lty='dashed', col='red')
lines(newx, preds[,2],lty='dashed', col='red')
abline(ns1, col='red')
points(lnF ~ dcsMeanDepth, data=data1)
summary(ns1)
confint(ns1)
min(data1$dcsMeanDepth)
max(data1$dcsMeanDepth)

graphNum=2
data2 = NewSubsample[NewSubsample$graph == graphNum,]
ns2 <- lm(lnF ~ dcsMeanDepth, data=data2)
newx <- seq(min(data2$dcsMeanDepth), max(data2$dcsMeanDepth), length.out=100)
preds <- predict(ns2, newdata = data.frame(dcsMeanDepth=newx), interval='confidence')
plot(data=data2, lnF ~ dcsMeanDepth)
polygon(c(rev(newx),newx),c(rev(preds[,3]),preds[,2]), col='grey80', border=NA)
lines(newx, preds[,3],lty='dashed', col='red')
lines(newx, preds[,2],lty='dashed', col='red')
abline(ns2, col='red')
points(lnF ~ dcsMeanDepth, data=data2)
summary(ns2)
confint(ns2)
min(data2$dcsMeanDepth)
max(data2$dcsMeanDepth)

graphNum=3
data3 = NewSubsample[NewSubsample$graph == graphNum,]
ns3 <- lm(lnF ~ dcsMeanDepth, data=data3)
newx <- seq(min(data3$dcsMeanDepth), max(data3$dcsMeanDepth), length.out=100)
preds <- predict(ns3, newdata = data.frame(dcsMeanDepth=newx), interval='confidence')
plot(data=data3, lnF ~ dcsMeanDepth)
polygon(c(rev(newx),newx),c(rev(preds[,3]),preds[,2]), col='grey80', border=NA)
lines(newx, preds[,3],lty='dashed', col='red')
lines(newx, preds[,2],lty='dashed', col='red')
abline(ns3, col='red')
points(lnF ~ dcsMeanDepth, data=data3)
summary(ns3)
confint(ns3)
min(data3$dcsMeanDepth)
max(data3$dcsMeanDepth)

ns4 <- lm(NewSubsample$lnF ~ NewSubsample$dcsMeanDepth)
newx <- seq(min(NewSubsample$dcsMeanDepth), max(NewSubsample$dcsMeanDepth), length.out=100)
preds <- predict(ns3, newdata = data.frame(dcsMeanDepth=newx), interval='confidence')
plot(NewSubsample$lnF ~ NewSubsample$dcsMeanDepth)
polygon(c(rev(newx),newx),c(rev(preds[,3]),preds[,2]), col='grey80', border=NA)
lines(newx, preds[,3],lty='dashed', col='red')
lines(newx, preds[,2],lty='dashed', col='red')
abline(ns3, col='red')
points(NewSubsample$lnF ~ NewSubsample$dcsMeanDepth)
summary(ns4)
confint(ns4)
min(NewSubsample$dcsMeanDepth)
max(NewSubsample$dcsMeanDepth)


NewSubsample <- read.csv("subsamp_3070157A1.csv")

graphNum=1
data1 = NewSubsample[NewSubsample$graph == graphNum,]
ns1 <- lm(lnF ~ dcsMeanDepth, data=data1)
newx <- seq(min(data1$dcsMeanDepth), max(data1$dcsMeanDepth), length.out=100)
preds <- predict(ns1, newdata = data.frame(dcsMeanDepth=newx), interval='confidence')
plot(data=data1, lnF ~ dcsMeanDepth)
polygon(c(rev(newx),newx),c(rev(preds[,3]),preds[,2]), col='grey80', border=NA)
lines(newx, preds[,3],lty='dashed', col='red')
lines(newx, preds[,2],lty='dashed', col='red')
abline(ns1, col='red')
points(lnF ~ dcsMeanDepth, data=data1)
summary(ns1)
confint(ns1)
min(data1$dcsMeanDepth)
max(data1$dcsMeanDepth)

graphNum=2
data2 = NewSubsample[NewSubsample$graph == graphNum,]
ns2 <- lm(lnF ~ dcsMeanDepth, data=data2)
newx <- seq(min(data2$dcsMeanDepth), max(data2$dcsMeanDepth), length.out=100)
preds <- predict(ns2, newdata = data.frame(dcsMeanDepth=newx), interval='confidence')
plot(data=data2, lnF ~ dcsMeanDepth)
polygon(c(rev(newx),newx),c(rev(preds[,3]),preds[,2]), col='grey80', border=NA)
lines(newx, preds[,3],lty='dashed', col='red')
lines(newx, preds[,2],lty='dashed', col='red')
abline(ns2, col='red')
points(lnF ~ dcsMeanDepth, data=data2)
summary(ns2)
confint(ns2)
min(data2$dcsMeanDepth)
max(data2$dcsMeanDepth)

graphNum=3
data3 = NewSubsample[NewSubsample$graph == graphNum,]
ns3 <- lm(lnF ~ dcsMeanDepth, data=data3)
newx <- seq(min(data3$dcsMeanDepth), max(data3$dcsMeanDepth), length.out=100)
preds <- predict(ns3, newdata = data.frame(dcsMeanDepth=newx), interval='confidence')
plot(data=data3, lnF ~ dcsMeanDepth)
polygon(c(rev(newx),newx),c(rev(preds[,3]),preds[,2]), col='grey80', border=NA)
lines(newx, preds[,3],lty='dashed', col='red')
lines(newx, preds[,2],lty='dashed', col='red')
abline(ns3, col='red')
points(lnF ~ dcsMeanDepth, data=data3)
summary(ns3)
confint(ns3)
min(data3$dcsMeanDepth)
max(data3$dcsMeanDepth)

ns4 <- lm(NewSubsample$lnF ~ NewSubsample$dcsMeanDepth)
newx <- seq(min(NewSubsample$dcsMeanDepth), max(NewSubsample$dcsMeanDepth), length.out=100)
preds <- predict(ns3, newdata = data.frame(dcsMeanDepth=newx), interval='confidence')
plot(NewSubsample$lnF ~ NewSubsample$dcsMeanDepth)
polygon(c(rev(newx),newx),c(rev(preds[,3]),preds[,2]), col='grey80', border=NA)
lines(newx, preds[,3],lty='dashed', col='red')
lines(newx, preds[,2],lty='dashed', col='red')
abline(ns3, col='red')
points(NewSubsample$lnF ~ NewSubsample$dcsMeanDepth)
summary(ns4)
confint(ns4)
min(NewSubsample$dcsMeanDepth)
max(NewSubsample$dcsMeanDepth)


NewSubsample <- read.csv("subsamp_3070570A1.csv")

graphNum=1
data1 = NewSubsample[NewSubsample$graph == graphNum,]
ns1 <- lm(lnF ~ dcsMeanDepth, data=data1)
newx <- seq(min(data1$dcsMeanDepth), max(data1$dcsMeanDepth), length.out=100)
preds <- predict(ns1, newdata = data.frame(dcsMeanDepth=newx), interval='confidence')
plot(data=data1, lnF ~ dcsMeanDepth)
polygon(c(rev(newx),newx),c(rev(preds[,3]),preds[,2]), col='grey80', border=NA)
lines(newx, preds[,3],lty='dashed', col='red')
lines(newx, preds[,2],lty='dashed', col='red')
abline(ns1, col='red')
points(lnF ~ dcsMeanDepth, data=data1)
summary(ns1)
confint(ns1)
min(data1$dcsMeanDepth)
max(data1$dcsMeanDepth)

graphNum=2
data2 = NewSubsample[NewSubsample$graph == graphNum,]
ns2 <- lm(lnF ~ dcsMeanDepth, data=data2)
newx <- seq(min(data2$dcsMeanDepth), max(data2$dcsMeanDepth), length.out=100)
preds <- predict(ns2, newdata = data.frame(dcsMeanDepth=newx), interval='confidence')
plot(data=data2, lnF ~ dcsMeanDepth)
polygon(c(rev(newx),newx),c(rev(preds[,3]),preds[,2]), col='grey80', border=NA)
lines(newx, preds[,3],lty='dashed', col='red')
lines(newx, preds[,2],lty='dashed', col='red')
abline(ns2, col='red')
points(lnF ~ dcsMeanDepth, data=data2)
summary(ns2)
confint(ns2)
min(data2$dcsMeanDepth)
max(data2$dcsMeanDepth)

graphNum=3
data3 = NewSubsample[NewSubsample$graph == graphNum,]
ns3 <- lm(lnF ~ dcsMeanDepth, data=data3)
newx <- seq(min(data3$dcsMeanDepth), max(data3$dcsMeanDepth), length.out=100)
preds <- predict(ns3, newdata = data.frame(dcsMeanDepth=newx), interval='confidence')
plot(data=data3, lnF ~ dcsMeanDepth)
polygon(c(rev(newx),newx),c(rev(preds[,3]),preds[,2]), col='grey80', border=NA)
lines(newx, preds[,3],lty='dashed', col='red')
lines(newx, preds[,2],lty='dashed', col='red')
abline(ns3, col='red')
points(lnF ~ dcsMeanDepth, data=data3)
summary(ns3)
confint(ns3)
min(data3$dcsMeanDepth)
max(data3$dcsMeanDepth)

ns4 <- lm(NewSubsample$lnF ~ NewSubsample$dcsMeanDepth)
newx <- seq(min(NewSubsample$dcsMeanDepth), max(NewSubsample$dcsMeanDepth), length.out=100)
preds <- predict(ns3, newdata = data.frame(dcsMeanDepth=newx), interval='confidence')
plot(NewSubsample$lnF ~ NewSubsample$dcsMeanDepth)
polygon(c(rev(newx),newx),c(rev(preds[,3]),preds[,2]), col='grey80', border=NA)
lines(newx, preds[,3],lty='dashed', col='red')
lines(newx, preds[,2],lty='dashed', col='red')
abline(ns3, col='red')
points(NewSubsample$lnF ~ NewSubsample$dcsMeanDepth)
summary(ns4)
confint(ns4)
min(NewSubsample$dcsMeanDepth)
max(NewSubsample$dcsMeanDepth)
